version: '3.4'

services:
  s_sql_server:
   user: root
   ports: 
     - 1433:1433
   environment:
     - ACCEPT_EULA=Y
     - MSSQL_SA_PASSWORD=strongPwd123+
   volumes:
     - sql_server_data:/var/opt/mssql
   restart: "on-failure"
   networks:
     - back-end-network

networks:
 back-end-network:
  driver: bridge
  external: false

volumes:
 sql_server_data:
 